### ISSUE TITLE
Getting an older version of the notebook for this lab

### ISSUE THREAD

**Issue by joeldmott** [learn-co-curriculum/dsc-logistic-regression-model-comparisons-lab#1]
## Link to Canvas

https://learning.flatironschool.com/courses/6536/assignments/241438?module_item_id=567737

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [x] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```
[20231130 - seemingly outdated Logistic Regression Model Comparisons - Lab.pdf](https://github.com/learn-co-curriculum/dsc-logistic-regression-model-comparisons-lab/files/13519670/20231130.-.seemingly.outdated.Logistic.Regression.Model.Comparisons.-.Lab.pdf)

I think I'm getting an older version of this lab's notebook when I open it in Canvas/Saturn Cloud. It's attached as a PDF here. I got some of the way through when a gradient descent function cell wouldn't ever output anything (it just kept running) and when I checked the solution, it looked like a substantially revised version of the notebook was there (also in the master branch). 
```

## What OS Are You Using?

- [ ] OS X
- [x] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Hello. So you need to run:

```
!rm index.ipynb
!bash /home/jovyan/.saturn/start.sh
```

in an empty cell at the top within Saturn Cloud. Shut down the kernel, and then reopen from Canvas; this will give you the updated version of the notebook. Your instructor should be able to assist you if needed.
